url: https://jvrunion.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: John Vincent Runion
email: jvrunion@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FE5C36
  secondary: 58A2C8 
  secondary-dark: 333

# Team names, titles and social links
people:
- name: John Vincent Runion
  pic: 4
  position: Principal
  social:
    - title: twitter
      url: http://twitter.com/dc_coder
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/dc_coder
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/dc_coder
  - title: bitbucket 
    url: http://bitbucket.org/jvrunion
  - title: github
    url: http://github.com/jvrunion

# Postal address (add as many lines as necessary)
address:
  - line: 5801 Sunderland Court
  - line: Alexandria, VA 22315

# Build settings
markdown: kramdown
permalink: pretty